name: mottai_flutter_app

repository: https://github.com/KosukeSaigusa/npo-mottai-matching-app

packages:
  - packages/**
  - '*'

scripts:
  clean:
    run: melos exec -- "flutter clean"

  pub:get:
    run: melos exec -- "flutter pub get"

  clean:pub:get:
    run: melos exec -- "flutter clean && flutter pub get"

  generate:
    run: melos exec --scope="mottai_matching_app" \
      "flutter pub run build_runner build --delete-conflicting-outputs && exit"

  generate:watch:
    run: melos exec --scope="mottai_matching_app" \
      "flutter pub run build_runner watch --delete-conflicting-outputs && exit"

  build:devios:
    run: melos exec --scope="mottai_matching_app" \
      "fab devios && exit"

  build:prodios:
    run: melos exec --scope="mottai_matching_app" \
      "fab prodios && exit"

  build:devandroid:
    run: melos exec --scope="mottai_matching_app" \
      "fab devandroid && exit"

  build:prodandroid:
    run: melos exec --scope="mobile" \
      "fab prodandroid && exit"

  build:dev:
    run: melos run build:devios && melos run build:devandroid

  build:prod:
    run: melos run build:prodios && melos run build:prodandroid
