name: mottai_flutter_app

repository: https://github.com/KosukeSaigusa/mottai-flutter-app

packages:
  - packages/**
  - '*'

sdkPath: .fvm/flutter_sdk

scripts:
  clean:
    run: melos exec -- "flutter clean"

  pg:
    run: melos exec -- "flutter pub get"

  clpg:
    run: melos exec -- "fvm flutter clean && fvm flutter pub get"

