name: dart_flutter_common
description: MOTTAI app Dart and Flutter common.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  image_picker: ^1.0.1
  intl: 0.18.1
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
