name: firebase_common
description: MOTTAI app firebase common.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  flutter:
    sdk: flutter
  flutterfire_gen_annotation: ^0.1.0-dev.1
  flutterfire_gen_utils: ^0.0.1-dev.2
  flutterfire_json_converters: ^0.0.5
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutterfire_gen: ^0.0.1-dev.4

flutter:
  uses-material-design: true
