name: mottai_flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.1
  cloud_functions: ^4.0.7
  mottai_commons:
    path: ../common
  cupertino_icons: ^1.0.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.3.0
  freezed_annotation: ^2.2.0
  gap: ^2.0.1
  geoflutterfire_plus:
    git:
      url: https://github.com/KosukeSaigusa/geoflutterfire_plus.git
      ref: main
  google_maps_flutter: ^2.2.3
  hooks_riverpod: ^2.1.3
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  pedantic_mono: ^1.20.1

flutter:
  uses-material-design: true
