name: mottai_flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.5.0
  cloud_functions: ^4.1.0
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  firebase_storage: ^11.1.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  gap: ^2.0.1
  geoflutterfire_plus:
    git:
      url: https://github.com/KosukeSaigusa/geoflutterfire_plus.git
      ref: main
  google_maps_flutter: ^2.2.5
  hooks_riverpod: ^2.3.2
  mottai_commons:
    path: ../common
  path_to_regexp: ^0.4.0
  simple_logger: ^1.9.0+2
  tuple: ^2.0.1
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

flutter:
  uses-material-design: true
