name: mottai_flutter_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  cached_network_image:
  cloud_firestore:
  cloud_functions:
  connectivity_plus:
  crypto:
  cupertino_icons:
  dart_geohash:
  firebase_analytics:
  firebase_auth:
  firebase_core:
  firebase_crashlytics:
  firebase_dynamic_links:
  firebase_messaging:
  firebase_storage:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_keyboard_visibility:
  flutter_line_sdk:
  flutter_localizations:
    sdk: flutter
  flutter_native_image:
  flutter_signin_button:
  flutter_spinkit:
  flutter_state_notifier:
  flutterfire_ui:
  font_awesome_flutter:
  freezed:
  freezed_annotation:
  gap:
  # geoflutterfire: ^3.0.3
  geoflutterfire:
    path: ../geoflutterfire
  geolocator:
  google_fonts:
  google_maps_flutter:
  google_sign_in:
  hooks_riverpod: ^2.0.0-dev.5
  image_cropper:
  image_picker:
  intl:
  json_annotation:
  keyboard_actions:
  ks_flutter_commons:
    path: ../ks_flutter_commons
  mottai_flutter_app_models:
    path: ../models
  package_info_plus:
  photo_view:
  rxdart:
  shared_preferences:
  sign_in_with_apple:
  state_notifier:
  url_launcher:
  uuid:
  wechat_assets_picker:

dev_dependencies:
  build_runner:
  flutter_launcher_icons:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/launcher_icon/launcher_icon.png'
