name: mottai_flutter_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  cached_network_image:
  cloud_firestore:
  cloud_functions:
  connectivity_plus:
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  dart_geohash: ^2.0.2
  firebase_analytics:
  firebase_auth:
  firebase_core:
  firebase_crashlytics:
  firebase_dynamic_links:
  firebase_messaging:
  firebase_storage:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_keyboard_visibility: ^5.2.0
  flutter_line_sdk: ^2.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_image: ^0.0.6+1
  flutter_signin_button: ^2.0.0
  flutter_spinkit:
  flutter_state_notifier: ^0.7.1
  flutterfire_ui:
  font_awesome_flutter:
  freezed:
  freezed_annotation:
  gap:
  # geoflutterfire: ^3.0.3
  geoflutterfire:
    path: ../geoflutterfire
  geolocator: ^8.2.0
  google_fonts:
  google_maps_flutter:
  google_sign_in:
  hooks_riverpod: ^2.0.0-dev.5
  image_cropper:
  image_picker:
  intl: ^0.17.0
  json_annotation:
  keyboard_actions:
  ks_flutter_commons:
    path: ../ks_flutter_commons
  mottai_flutter_app_models:
    path: ../models
  package_info_plus:
  photo_view:
  rxdart: ^0.27.3
  shared_preferences:
  sign_in_with_apple:
  state_notifier: ^0.7.1
  url_launcher:
  uuid:
  wechat_assets_picker: ^6.3.0

dev_dependencies:
  build_runner:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/launcher_icon/launcher_icon.png'
