name: mottai_commons
description: Mottai common module
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: '>=3.3.9'

dependencies:
  cloud_firestore: ^4.5.0
  firebase_core: ^2.9.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

