name: mottai_commons
description: Mottai common module
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: '>=3.3.9'

dependencies:
  freezed_annotation:
  json_annotation:

dev_dependencies:
  build_runner:
  freezed:
  json_serializable:
  pedantic_mono:
